name: 1_wf_be_build

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      DOCKER_URL:
        required: true
        type: string
      DOCKER_USERNAME:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
    outputs:
      IMAGE_TAG:
        value: ${{ jobs.build.outputs.IMAGE_TAG }}

jobs:
  build:
    name: Build ${{ inputs.APP_NAME }}
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    outputs:
      IMAGE_TAG: ${{ steps.out_tag.outputs.IMAGE_TAG }}
    env:
      IMAGE_TAG: $(git rev-parse --short HEAD)
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Dockerhub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_URL }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image ${{ inputs.APP_NAME }}
        working-directory: ${{ inputs.APP_NAME }}
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ inputs.APP_NAME }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ vars.DOCKER_USERNAME }}/${{ inputs.APP_NAME }}:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_USERNAME }}/${{ inputs.APP_NAME }}:latest

      - name: Push Docker Image ${{ inputs.APP_NAME }}
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/${{ inputs.APP_NAME }}:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ inputs.APP_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Output IMAGE_TAG for Deployment steps
        id: out_tag
        run: |
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"
