name: wf_be_build

on:
  push:
    branches: ["main"]
    # paths:
    #   - "api/**"
    #   - "consumer/**"
    #   - "crawler/**"
    #   - "migrate/**"

jobs:
  build:
    name: Build Image BE
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    env:
      IMAGE_TAG: $(git rev-parse --short HEAD)
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Dockerhub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_URL }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Overwrite environment build variables
        run: |
          cat ./api/.env.container > ./api/.env
          cat ./consumer/.env.container > ./consumer/.env
          cat ./crawler/.env.container > ./crawler/.env
          cat ./migrate/.env.container > ./migrate/.env

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/crawler-api:${{ env.IMAGE_TAG }} ./api
          docker tag ${{ vars.DOCKER_USERNAME }}/crawler-api:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_USERNAME }}/crawler-api:latest

          docker build -t ${{ vars.DOCKER_USERNAME }}/consumer-app:${{ env.IMAGE_TAG }} ./consumer
          docker tag ${{ vars.DOCKER_USERNAME }}/consumer-app:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_USERNAME }}/consumer-app:latest

          docker build -t ${{ vars.DOCKER_USERNAME }}/crawler-app:${{ env.IMAGE_TAG }} ./crawler
          docker tag ${{ vars.DOCKER_USERNAME }}/crawler-app:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_USERNAME }}/crawler-app:latest

          docker build -t ${{ vars.DOCKER_USERNAME }}/crawler-app-migrate:${{ env.IMAGE_TAG }} ./migrate
          docker tag ${{ vars.DOCKER_USERNAME }}/crawler-app-migrate:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_USERNAME }}/crawler-app-migrate:latest
      
      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/crawler-api:latest
          docker push ${{ vars.DOCKER_USERNAME }}/crawler-api:${{ env.IMAGE_TAG }}

          docker push ${{ vars.DOCKER_USERNAME }}/consumer-app:latest
          docker push ${{ vars.DOCKER_USERNAME }}/consumer-app:${{ env.IMAGE_TAG }}

          docker push ${{ vars.DOCKER_USERNAME }}/crawler-app:latest
          docker push ${{ vars.DOCKER_USERNAME }}/crawler-app:${{ env.IMAGE_TAG }}

          docker push ${{ vars.DOCKER_USERNAME }}/crawler-app-migrate:latest
          docker push ${{ vars.DOCKER_USERNAME }}/crawler-app-migrate:${{ env.IMAGE_TAG }}
